services:
  - docker
jobs:
  include:
    - stage: "Maven build free-service"
      dist: trusty
      language: java
      jdk: oraclejdk8
      before_script:
        - cd ./services/free-service
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - docker build -t yvesrut/msr-free-service:latest .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push yvesrut/msr-free-service:latest
