services:
  - docker
jobs:
  include:
    - stage: "Maven build free-service"
      dist: trusty
      language: java
      jdk: oraclejdk8
      before_script:
        - cd ./services/free-service
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - docker build -t noahcha/msr-free-service:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push noahcha/msr-free-service:latest
