version: '3.7'
services:
 inferenceservice:
   build:
     context: ./services/inference-service
     dockerfile: Dockerfile
   volumes:
     - './services/inference-service:/usr/src/app'
   ports:
     - 5004:5000
   environment:
     - FLASK_ENV=development
     - APP_SETTINGS=src.config.DevelopmentConfig
     - DATABASE_URL=postgresql://admin:admin@movie-recommender-system_database_1:5432/mrs
   networks:
     - mrs
 database:
   image: postgres:latest
   expose:
     - 5432
   environment:
     POSTGRES_DB: mrs
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
   volumes:
     - C:\Users\yvesr\Desktop\fs21_projects\movie-recommender-system\tbl_rating\:/tbl_rating/
   networks:
     - mrs

networks:
  mrs:
    external: true